-- 
-- Problem 140: Modified Fibonacci golden nuggets
-- (Published on Saturday, 3rd February 2007, 07:00 am; Solved by 2377)
-- 
--     Consider the infinite polynomial series A_{G}(x) = xG_{1} +
-- 	x^{2}G_{2} + x^{3}G_{3} + ..., where G_{k} is the kth term of the
-- 	second order recurrence relation G_{k} = G_{k−1} + G_{k−2}, G_{1} =
-- 	1 and G_{2} = 4; that is, 1, 4, 5, 9, 14, 23, ... .
-- 
--     For this problem we shall be concerned with values of x for
-- 	which A_{G}(x) is a positive integer.
-- 
--     The corresponding values of x for the first five natural numbers
-- 	are shown below.
-- 
--             *x* *A_{G}(x)*
--     (√5−1)/4          1
--         2/5       2
--     (√22−2)/6         3
--     (√137−5)/14       4
--         1/2       5
-- 
-- 
--     We shall call A_{G}(x) a golden nugget if x is rational, because
-- 	they become increasingly rarer; for example, the 20th golden nugget
-- 	is 211345365.
-- 
--     Find the sum of the first thirty golden nuggets.
