-- 
-- Problem 85: Counting rectangles
-- (Published on Friday, 17th December 2004, 06:00 pm; Solved by 13966)
-- 
--     By counting carefully it can be seen that a rectangular grid
-- 	measuring 3 by 2 contains eighteen rectangles:
-- 
-- <img alt="" src="project/images/p085.gif"/>
--     Although there exists no rectangular grid that contains exactly
-- 	two million rectangles, find the area of the grid with the nearest
-- 	solution.
