-- 
-- Problem 110: Diophantine reciprocals II
-- (Published on Friday, 2nd December 2005, 06:00 pm; Solved by 4761)
-- 
--     In the following equation x, y, and n are positive integers.
-- 
--             1
-- x        +      1
-- y        =      1
-- n
-- 
-- 
--     It can be verified that when n = 1260 there are 113 distinct
-- 	solutions and this is the least value of n for which the total
-- 	number of distinct solutions exceeds one hundred.
-- 
--     What is the least value of n for which the number of distinct
-- 	solutions exceeds four million?
-- 
--     NOTE: This problem is a much more difficult version of [Problem
-- 	108](problem=108) and as it is well beyond the limitations of a
-- 	brute force approach it requires a clever implementation.
