-- 
-- Problem 104: Pandigital Fibonacci ends
-- (Published on Friday, 9th September 2005, 06:00 pm; Solved by 9452)
-- 
--     The Fibonacci sequence is defined by the recurrence relation:
-- F_{n} = F_{n−1} + F_{n−2}, where F_{1} = 1 and F_{2} = 1.
--     It turns out that F_{541}, which contains 113 digits, is the
-- 	first Fibonacci number for which the last nine digits are 1-9
-- 	pandigital (contain all the digits 1 to 9, but not necessarily in
-- 	order). And F_{2749}, which contains 575 digits, is the first
-- 	Fibonacci number for which the first nine digits are 1-9
-- 	pandigital.
-- 
--     Given that F_{k} is the first Fibonacci number for which the
-- 	first nine digits AND the last nine digits are 1-9 pandigital, find
-- 	k.
