-- 
-- Problem 164: Numbers for which no three consecutive digits have a sum greater than a given value
-- (Published on Saturday, 20th October 2007, 06:00 am; Solved by 3457)
-- 
--     How many 20 digit numbers n (without any leading zero) exist
-- 	such that no three consecutive digits of n have a sum greater than
-- 	9?
