-- 
-- Problem 181: Investigating in how many ways objects of two different colours can be grouped
-- (Published on Saturday, 9th February 2008, 01:00 pm; Solved by 1118)
-- 
--     Having three black objects B and one white object W they can be
-- 	grouped in 7 ways like this:
-- 
--          (BBBW) (B,BBW) (B,B,BW)    (B,B,B,W)   (B,BB,W)    (BBB,W)
-- 	(BB,BW)
-- 
-- 
--     In how many ways can sixty black objects B and forty white
-- 	objects W be  thus grouped?
