-- 
-- Problem 184: Triangles containing the origin
-- (Published on Friday, 29th February 2008, 09:00 pm; Solved by 930)
-- 
--     Consider the set I_{r} of points (x,y) with integer co-ordinates
-- 	in the interior of the circle with radius r, centered at the
-- 	origin, i.e. x^{2} + y^{2} < r^{2}.
-- 
--     For a radius of 2, I_{2} contains the nine points (0,0), (1,0),
-- 	(1,1), (0,1), (-1,1), (-1,0), (-1,-1), (0,-1) and (1,-1). There are
-- 	eight triangles having all three vertices in I_{2} which contain
-- 	the origin in the interior. Two of them are shown below, the others
-- 	are obtained from these by rotation.
-- 
-- 
-- <img alt="" src="project/images/p184.gif"/>
-- 
--     For a radius of 3, there are 360 triangles containing the origin
-- 	in the interior and having all vertices in I_{3} and for I_{5} the
-- 	number is 10600.
-- 
--     How many triangles are there containing the origin in the
-- 	interior and having all three vertices in I_{105}?
