-- 
-- Problem 172: Investigating numbers with few repeated digits
-- (Published on Saturday, 15th December 2007, 09:00 am; Solved by 2218)
-- 
--     How many 18-digit numbers n (without leading zeros) are there
-- 	such that no digit occurs more than three times in n?
