--
-- Problem 15: Lattice paths
-- (Published on Friday, 19th April 2002, 06:00 pm; Solved by 97366)
--
--     Starting in the top left corner of a 2×2 grid, and only being
-- 	able to move to the right and down, there are exactly 6 routes to
-- 	the bottom right corner.
--
-- <img alt="" src="project/images/p015.gif"/>
--     How many such routes are there through a 20×20 grid?
