#
# Problem 2: Even Fibonacci numbers
# (Published on Friday, 19th October 2001, 06:00 pm; Solved by 267974)
#
#     Each new term in the Fibonacci sequence is generated by adding
# 	the previous two terms. By starting with 1 and 2, the first 10
# 	terms will be:
#
#     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#     By considering the terms in the Fibonacci sequence whose values
# 	do not exceed four million, find the sum of the even-valued terms.
#
# Note: This problem has been changed recently, please check that you
# 	are using the right parameters.

n = int(4e6)

f1 = 0
f2 = 1
s = 0

while f1 < n:
    if f1 % 2 == 1:
        s += f1

    f2 += f1
    f1, f2 = f2, f1

print(s)

